#!/usr/bin/env python3
"""Build a progress dashboard for the local reading library."""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from import_notion_resource_library import canonicalize_url, load_resources


ROOT = Path(__file__).resolve().parents[1]
NOTES = ROOT / "wiki" / "reading" / "notes"
OUTPUT = ROOT / "wiki" / "reading" / "progress.md"


@dataclass(frozen=True)
class Note:
    path: Path
    title: str
    description: str
    resource: str
    resource_aliases: tuple[str, ...]
    notion: str
    notion_aliases: tuple[str, ...]
    status: str


def parse_inline_list(value: str) -> tuple[str, ...]:
    value = value.strip()
    if not (value.startswith("[") and value.endswith("]")):
        return ()
    return tuple(
        item.strip().strip("\"'")
        for item in value[1:-1].split(",")
        if item.strip().strip("\"'")
    )


def parse_frontmatter(path: Path) -> Note:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, re.DOTALL)
    values: dict[str, str] = {}
    if match:
        for line in match.group(1).splitlines():
            if ":" not in line:
                continue
            key, value = line.split(":", 1)
            values[key.strip()] = value.strip().strip("\"'")
    return Note(
        path=path,
        title=values.get("title", path.stem),
        description=values.get("description", ""),
        resource=values.get("resource", ""),
        resource_aliases=parse_inline_list(values.get("resource_aliases", "")),
        notion=values.get("notion", ""),
        notion_aliases=parse_inline_list(values.get("notion_aliases", "")),
        status=values.get("status", "unknown"),
    )


def escape_table(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ")


def note_link(note: Note) -> str:
    return f"[{escape_table(note.title)}](notes/{note.path.name})"


def main() -> None:
    resources = load_resources()
    notes = [
        parse_frontmatter(path)
        for path in sorted(NOTES.glob("*.md"))
        if path.name != "index.md"
    ]

    by_notion: dict[str, Note] = {}
    by_resource: dict[str, Note] = {}
    for note in notes:
        for notion_url in (note.notion, *note.notion_aliases):
            if notion_url:
                by_notion[notion_url] = note
        for resource_url in (note.resource, *note.resource_aliases):
            if resource_url:
                by_resource[canonicalize_url(resource_url).casefold()] = note

    matches: list[tuple[object, Note | None]] = []
    used_notes: set[Path] = set()
    for resource in resources:
        note = next(
            (
                by_notion[notion_url]
                for notion_url in resource.notion_urls
                if notion_url in by_notion
            ),
            None,
        )
        if note is None and resource.canonical_url:
            note = by_resource.get(resource.canonical_url.casefold())
        matches.append((resource, note))
        if note:
            used_notes.add(note.path)

    completed_statuses = {"summarized"}
    blocked_statuses = {"access-limited", "unavailable", "needs-review"}
    completed = [(resource, note) for resource, note in matches if note and note.status in completed_statuses]
    blocked = [(resource, note) for resource, note in matches if note and note.status in blocked_statuses]
    pending = [(resource, note) for resource, note in matches if note is None]
    other = [
        (resource, note)
        for resource, note in matches
        if note and note.status not in completed_statuses | blocked_statuses
    ]

    category_totals = Counter(resource.category for resource in resources)
    category_done = Counter(
        resource.category for resource, note in matches if note is not None
    )
    category_blocked = Counter(resource.category for resource, note in blocked)

    lines = [
        "---",
        "type: Reference",
        "title: 읽기 자료 전체 처리 현황",
        f"description: 중복 제거된 읽기 자료 {len(resources)}개의 상세 노트 작성 상태와 접근 실패 사유",
        "tags: [reading, progress, maintenance]",
        "timestamp: 2026-07-24",
        "status: active",
        "---",
        "",
        "<!-- Generated by scripts/build_reading_progress.py. -->",
        "",
        "# 전체 현황",
        "",
        f"- 전체 고유 자료: {len(resources)}개",
        f"- 요약 완료: {len(completed)}개",
        f"- 접근 제한 또는 원문 소실: {len(blocked)}개",
        f"- 처리 대기: {len(pending)}개",
        f"- 기타 상태: {len(other)}개",
        "",
        "완료 수에는 실제 원문을 확인해 재작성한 노트만 포함합니다. 접근 제한 자료는 완료로 세지 않고, "
        "사용자가 대체 링크나 원문을 제공하면 다시 처리합니다.",
        "",
        "# 분류별 진행률",
        "",
        "| 분류 | 전체 | 노트 작성 | 접근 제한 | 대기 |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for category, total in category_totals.most_common():
        done = category_done[category]
        limited = category_blocked[category]
        lines.append(
            f"| {category} | {total} | {done} | {limited} | {total - done} |"
        )

    lines.extend(
        [
            "",
            "# 접근 제한 및 확인 필요",
            "",
        ]
    )
    if not blocked:
        lines.append("- 없음")
    else:
        for resource, note in blocked:
            source = resource.source_url or "원문 URL 없음"
            notion = resource.notion_urls[0] if resource.notion_urls else ""
            lines.extend(
                [
                    f"## {note_link(note)}",
                    "",
                    f"- 상태: `{note.status}`",
                    f"- 막힌 이유: {note.description or '노트 본문에서 상세 사유 확인'}",
                    f"- 저장된 원문: {source}",
                    f"- Notion 항목: {notion or '없음'}",
                    "",
                ]
            )

    lines.extend(
        [
            "# 작성된 노트",
            "",
            "| 자료 | 상태 | 추가일 | 분류 |",
            "| --- | --- | --- | --- |",
        ]
    )
    for resource, note in [
        (resource, note) for resource, note in matches if note is not None
    ]:
        lines.append(
            f"| {note_link(note)} | `{note.status}` | "
            f"{resource.date_added or '-'} | {resource.category} |"
        )

    orphan_notes = [note for note in notes if note.path not in used_notes]
    if orphan_notes:
        lines.extend(
            [
                "",
                "# 원본 목록과 연결되지 않은 노트",
                "",
            ]
        )
        lines.extend(f"- {note_link(note)}" for note in orphan_notes)

    if pending:
        next_steps = [
            f"- 남은 {len(pending)}개는 최신 항목부터 배치별로 원문을 확인해 작성합니다.",
            "- 원문이 열리지 않거나 본문을 식별할 수 없으면 추측하지 않고 이 문서에 이유를 남깁니다.",
            "- 전체 대기열은 [읽기 체크리스트](inbox.md)에서 확인할 수 있습니다.",
        ]
    else:
        next_steps = [
            "- 전체 고유 자료의 1차 처리를 완료했습니다.",
            f"- 접근 제한 또는 원문 소실 {len(blocked)}개는 대체 링크나 원문이 추가되면 다시 확인합니다.",
            "- 새 Notion 자료를 가져온 뒤 이 스크립트를 다시 실행해 후속 대기 항목을 확인합니다.",
        ]
    lines.extend(["", "# 다음 작업", "", *next_steps])
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    print(
        f"total={len(resources)} completed={len(completed)} "
        f"blocked={len(blocked)} pending={len(pending)} "
        f"other={len(other)} orphan_notes={len(orphan_notes)}"
    )


if __name__ == "__main__":
    main()
